### ISSUE TITLE
Configuration & documentation issues

### ISSUE THREAD

**Issue by fischer-felix** [austozi/docker-fdroidserver#1]
Hi, just stumbled upon this because I also wanted to have a repo for some of my apps.

It seems like the nginx web server is never properly configured to show the webui.
When deploying it using the docker compose from [here](https://github.com/austozi/selfhosted/tree/main/fdroidserver), all I see is this:
![Screenshot_2023 01 01_18:16:19](https://user-images.githubusercontent.com/65448408/210179319-e333a5bf-a8a1-459c-bb71-b7c2796e42c9.png)

After a bit of digging, I was able to locate the html file for this in `/config/www/`.
Upon investigating the nginx configuration files, I noticed, that in order to see the page with the qr code, the webroot in `/config/nginx/site-confs/default.conf` needs to be set to `/config/fdroid/repo` instead of `/config/www`.

Additionally, the updates directory in `/usr/local/bin/refresh` is missconfigured.
By default, `UPDATES_DIR` is set to `/custom-cont-init.d`, however it should be `/config/fdroid/updates`.

In tems of documentation, it might be worth mentioning that you can use http basic auth to secure a public facing instance (I personally am using access lists in nginx proxy manager, but there are other options too).

**Comment by austozi** [comment]
Thanks for the bug report. Sorry it's taken me so long to respond. The bugs should have been fixed in the latest release.

The bugs were a result of me updating the dockerfile (due to upstream changes in the nginx image) but didn't have time to update the installation instructions accordingly. Over time I simply forgot.

I also hadn't realised I wasn't the only user of this image. Otherwise, I would have been more diligent with the documentation. 

If you still use this and have anything to add to improve this project, I welcome pull requests.
